### ISSUE TITLE
Flash of unstyled content during dev

### ISSUE THREAD

**Issue by PierBover** [marko-js/examples#22]
I'm trying the `vite-fastify` demo app.

During dev, whenever I refresh the page, I see a flash of unstyled content. After building and doing `npm run start` this disappears.

Is there a way to prevent this?

**Comment by DylanPiercey** [comment]
Sadly this is a [limitation fo Vite](https://github.com/vitejs/vite/issues/2013#issuecomment-778675386). At one point I explored some of the potential solutions people were putting forward but did not have much luck. If there is some work around we'd happily do what we can to make it work for the Marko examples.

**Comment by PierBover** [comment]
Thanks @DylanPiercey !
