### ISSUE TITLE
vite-fastify is not working 

### ISSUE THREAD

**Issue by peterluo8888** [marko-js/examples#40]
TypeError: Cannot read properties of undefined (reading 'Symbol(fastify.state)')
    at ready (C:\Users\Administrator\Downloads\examples-master\examples-master\node_modules\fastify\fastify.js:580:13)
    at file:///C:/Users/Administrator/Downloads/examples-master/examples-master/examples/vite-fastify/index.js:22:15

**Comment by mikko-severo** [comment]
Anyone have a solution to this?

**Comment by mikko-severo** [comment]
> Anyone have a solution to this?

I got it working by updating all the devDep and dep.  Only updating the fastify to ver 4.24.3, after that it failed to work.

**Comment by DylanPiercey** [comment]
Fixed in the latest `vite-fastify` example. The fix can be seen here https://github.com/marko-js/examples/commit/cc2b3dc08c07534a6d40e2cdc4d9b86810ae2fd9#diff-377a292a47bf578178bddcb0899488cf5c2352818769e8825febbe6b9472841eL21-L23
